repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: double-quote-string-fixer
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/best-doctor/pre-commit-hooks
    rev: v1.0.11
    hooks:
    - id: mccabe-complexity
      name: Check functions complexity
      language: python
    - id: line-count
      name: Check number of lines in python files
      language: python


  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
    - id: black

  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort
      args:
        - src/
      language: system
      pass_filenames: false


  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.1
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      pass_filenames: false
      args:
        - src/
        - --source-roots=src/
        - --disable=no-member
        - --disable=invalid-name

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.14.0
    hooks:
    - id: reorder-python-imports
      name: Reorder imports
      pass_filenames: false
      args:
        - "--application-directories=src/"

  - repo: local
    hooks:
    - id: pyright
      name: pyright
      entry: pyright
      language: system
      pass_filenames: false
      args:
        - src/

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        args:
          - src/
        pass_filenames: false
        language: system
